### ISSUE TITLE
appPath not used when deploying as part of larger express app

### ISSUE THREAD

**Issue by jcfergus** [jsreport/jsreport#139] opened 2015-10-27 21:00 UTC
I'm trying to deploy jsreport as part of a larger express app, ideally in a subpath of the app, per http://jsreport.net/learn/adapting-jsreport.  I have it up and running, if I access http://myapp.domain.com/ I get the jsreport UI.  I would like, however, for jsreport to live entirely under http://myapp.domain.com/reporting/, so that I can host the rest of my app at the root directory.  I've tried setting 'appPath' to '/reporting' in my config JSON, but that does not appear to make a difference.  Looking at the code, it doesn't look like this capability is built in ... am I missing something?

**Comment by bjrmatos** [comment] 2015-10-27 22:37
interesting.. seems you're right, i don't see `appPath` [being used](https://github.com/jsreport/jsreport/blob/master/extension/express/lib/reporter.express.js#L132) at least in express initialization.. i will dive into it when I come back home

**Comment by jcfergus** [comment] 2015-10-28 02:24
I've got a patch I cobbled together - after I bang on it a little more tomorrow to make sure it works, I'll submit it for you to roll in if you want.

**Comment by bjrmatos** [comment] 2015-10-28 05:46
@jcfergus sure, lets see :+1: 

ok, after searching a little more i see that the intended behavior of `appPath` was to be a prefix for URLs, but jsreport is not using it for route mounting, @pofider am i right? `appPath` have a use case and totally perfect to be an option for url prefix, deserves its own option.. 

..now we are talking about jsreport mounting inside express

i didn't dive into that part of jsreport yet but, is there anything stopped us to do something like..

```js
var jsreport = require('jsreport'),
      express = require('express'),
      app = express();

// after custom application routes
....

app.use('/reporting', jsreport.app());

```

i think this can be done and i'm sure there are ways to make it work, i'm just throwing an idea, because set it up this way is more the "express way" :)

**Comment by bjrmatos** [comment] 2015-10-28 05:48
and also i think it will make more clear how to do jsreport's vhost behind a subdomain

**Comment by pofider** [comment] 2015-10-28 10:01
You guys found it right. It was not the intention of `appPath` to mount the routes, but just prefix urls...

However you can provide your express app instance to which jsreport mounts through config. If you need to mount to the particular path, you can create dedicated express app instance for it...
```js
var jsreport = require('jsreport'),
    express = require('express');

var app = express();

app.get('/', function (req, res) {
  res.send('Hello from the main application');
});

var reportingApp = express();
app.use('/reporting', reportingApp);

jsreport.bootstrapper({
  rootDirectory: __dirname,
  express: { app :reportingApp } 
}).start().then(function() {
  app.listen(3000);
});
```
Isn't this suitable enough?

**Comment by jcfergus** [comment] 2015-10-28 13:49
Ah, well, that's quite a bit simpler than my patch.  :-)  I thought it seemed like there should be a simpler way to do that, but couldn't come up with it yesterday.  I'll give this a try.

**Comment by bjrmatos** [comment] 2015-10-28 16:21
> However you can provide your express app instance to which jsreport mounts through config. If you need to mount to the particular path, you can create dedicated express app instance for it...

oh god, is really simple!! (shame on me for not seeing that before..), but maybe adding an example to the docs (like the example provied by @pofider) would help other persons with the same confusion, @jcfergus would you like to do your first contribution to jsreport? :)

**Comment by jcfergus** [comment] 2015-10-28 17:49
I can do that.  Give me a couple days to get it written up.  :-)

**Comment by jcfergus** [comment] 2015-10-30 20:38
So can anyone else confirm that if you set it up the way @pofider describes above, and enable authentication, it stops working?  (Just hangs when I go to http://localhost:[PORT]/reporting after I've logged in.) That's the behavior I'm seeing.  This is my server.js:

```
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var jsrender = require('node-jsrender');
var jsreport = require('jsreport');
var fs = require('fs');
var util = require('util');

var express = require('express');
var app = express();

jsrender.express('html', app);
app.set('view engine', 'html' )

app.set('views', path.join(__dirname, 'server/views' ));

var reportingApp = express();

app.use('/reporting', reportingApp);

jsreport.bootstrapper({
    rootDirectory: __dirname,
    express : { app : reportingApp }
}).start().then(function() {
    var listener = app.listen( process.env.PORT, function () {
        console.log('Listening on port ' + listener.address().port);
    });
});
```

I'd like for someone to at least verify that it's not something on my end.  Unfortunately I've spent a fair amount of time trying to figure out where it's hanging, and am stumped on it.

**Comment by pofider** [comment] 2015-10-30 21:03
You mean jsreport authentication or your own one?

jsreport authentication is actually using `appPath` to do the login post to the right path. Does it help to add it? This is what works for me:

```js
jsreport.bootstrapper({
    rootDirectory: __dirname,
    express : { app : reportingApp },
    appPath: "/reporting",
    "authentication" : {
    "cookieSession": {
      "secret": "dasd321as56d1sd5s61vdv32"
    },
    "admin": {
      "username" : "admin",
      "password": "password"
    }
  },
}).start().then(function() {
    var listener = app.listen( 3000, function () {
        console.log('Listening on port ' + listener.address().port);
    });
});
```

**Comment by jcfergus** [comment] 2015-10-30 23:39
jsreport authentication.  I had the appPath set in my .conf file (along with the authentication settings), but have also tried doing it as you did above.  The exact behavior is that if I clear my cookies, when go to localhost:[port]/reporting, I get the login form, then if I enter my admin username and password I get redirected to /reporting as expected.  However, I never get a response back - the browser just decides after a couple minutes that the connection was closed without receiving data. The session cookie does get set, however, as I don't get the login form if I try again to load the page, just the "no data".    I've created a pastebin of the log here:  http://pastebin.com/aN5N9J8q

**Comment by bjrmatos** [comment] 2015-10-30 23:54
just curious.. can you try using `app.use('/reporting', reportingApp); ` as your first route setup? or it is already the first? just curious because i see ` body-parser:json body already parsed +1ms` in your logs

**Comment by pofider** [comment] 2015-10-31 09:13
Ups...

You use `NODE_ENV=dev` and only `NODE_ENV=development` or `NODE_ENV=production` works. Otherwise it hangs without an error message. (https://github.com/jsreport/jsreport/blob/master/extension/express/lib/routes.js#L100)

Sorry for your time. My fault. I will fix this right away.

**Comment by bjrmatos** [comment] 2015-10-31 19:09
what a lovely condition :smile:

**Comment by jcfergus** [comment] 2015-10-31 22:25
Phew.  Thank you - I'm relieved to know that I'm not just going insane.  

Can I suggest that IMHO, having it default to non-production unless NODE_ENV=production would be the ideal behavior, and having it load [NODE_ENV].config.json in bootstrapper.js would be great.

**Comment by bjrmatos** [comment] 2015-10-31 22:51
yeah, the condition should be

```js
        if (options.mode === "production")
            res.render(path.join(__dirname, '../public/views', 'root_built.html'), options);
        else 
           res.render(path.join(__dirname, '../public/views', 'root_dev.html'), options);
```

**Comment by bjrmatos** [comment] 2015-12-01 05:21
Closing the issue because it is solved :)

**Closed by bjrmatos** 2015-12-01 05:21 UTC
