### ISSUE TITLE
XLSX download via Docker jsreport/jsreport:1.7.0-full results in corrupt file

### ISSUE THREAD

**Issue by drmikecrowe** [jsreport/jsreport#312] opened 2017-07-21 11:51 UTC
It started with [my forum post](https://forum.jsreport.net/topic/191/converting-0-13-2-xlsx-template-to-1-x/11), and since this appears to a docker issue, opening an issue.

Using [this playground example](https://playground.jsreport.net/studio/workspace/Hy7m2WABZ/13), the file downloaded is corrupt if you are running jsreport via a Docker container.

If I install/run jsreport locally using the same configuration, same application API calls (or using the studio), download works fine w/o an issue (npm install, jsreport init, jsreport start).

#### LibreOffice Errors

![Error #1](https://ibin.co/3U12esgwtbm4.png)

![Error #1](https://ibin.co/3U12xImkjCRk.png)

#### Setup
Starting the docker image using composer file:

    jsreport:
      hostname: jsreport
      image: jsreport/jsreport:1.7.0-full
      restart: always
      ports:
        - "2945:2945"
      volumes:
        - ./new-containers/jsreport-home:/jsreport
      dns:
        - 8.8.8.8

Configuration:

    {
      "certificate": {
        "key": "certificates/jsreport.net.key",
        "cert": "certificates/jsreport.net.cert"
      },
      "connectionString": { "name": "fs" },
      "httpsPort": 2945,
      "logger": {
        "console": {
          "transport": "console",
          "level": "debug"
        }
      },
      "express.inputRequestLimit": "50mb",
      "blobStorage": "fileSystem",
      "phantom": {
        "strategy": "dedicated-process",
        "timeout": 60000
      },
      "tasks": {
        "strategy": "dedicated-process",
        "timeout": 10000,
        "allowedModules": []
      },
      "scripts": {
        "allowedModules": [],
        "timeout": 60000
      }
    }

**Comment by bjrmatos** [comment] 2017-07-21 17:56
i can confirm that the downloaded xlsx report is corrupted when using docker, i will try to investigate the issue. thnks for the report.

attaching a jsreport backup if someone wants to try the issue with the same case of the playground:

[xlsx-issue.zip](https://github.com/jsreport/jsreport/files/1166329/xlsx-issue.zip)

**Comment by bjrmatos** [comment] 2017-07-21 18:06
the weird thing is if you download the xlsx report directly from Excel online then the file is ok.

<img width="956" alt="captura de pantalla 2017-07-21 a las 1 05 15 p m" src="https://user-images.githubusercontent.com/4262050/28476326-4bde2418-6e15-11e7-99fa-918d87964988.png">

**Comment by drmikecrowe** [comment] 2017-07-21 18:09
Yep, I even did a hexdiff between the online working version and the failing one from docker.  It didn't give me any clues.

I thought it might be an internal file system issue too, so I tried mapping a local directory to /tmp in the container, and that didn't affect it either.

**Comment by bjrmatos** [comment] 2017-07-21 18:15
yes, let me know if you find something, i will try to find the problem, maybe it is related with some encoding issue while transfering the file in the download request.

**Comment by pofider** [comment] 2017-07-25 09:05
I see another Tom Clancy writer growing up here :)

The problem is now clear, thank you for digging it out.

I'm wondering why we execute the recipe in the `afterTemplatingEnginesExecuted ` [here](https://github.com/jsreport/jsreport-xlsx/blob/master/src/index.js#L83) instead of as normal recipe [here](https://github.com/jsreport/jsreport-xlsx/blob/master/src/index.js#L83). Changing it doesn't affect the functionality for me, all tests are green, but need to think if there is a reason for handling it in `afterTemplatingEnginesExecuted`.

**Comment by pofider** [comment] 2017-08-06 15:54
I release [jsreport-xlsx@1.4.0](https://github.com/jsreport/jsreport-xlsx/releases) with fix. It should be part of the upcoming `jsreport@1.8.0` in the next days.

**Comment by pofider** [comment] 2017-08-11 17:09
Released in 1.8.1

**Closed by pofider** 2017-08-11 17:09 UTC
Labels: bug
