### ISSUE TITLE
Unable to preview report on Ubuntu

### ISSUE THREAD

**Issue by 1Map** [jsreport/jsreport#888] opened 2022-02-23 13:19 UTC
My report renders perfect on my Windows PC, but on the Ubuntu server it gives an error (Basically immidiately):

```
preview error
Navigation failed because browser has disconnected!
Error: Navigation failed because browser has disconnected!
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/onemapjsreport/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
```

I followed the installation instructions and run the Orders Sample.  

```
npm install -g @jsreport/jsreport-cli
jsreport init
jsreport configure
jsreport start
```

Any template with an external url in the template gives this type of error.  For example the stylesheet link to metro.min.css as below:

```
<html lang="en">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/metro/4.1.5/css/metro.min.css">
        .....
```

**SECOND TEST EXAMPLE**

Run this on chrome-pdf recipe with wait for printing trigger selected:

```
<html lang="en">

<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <style>
        html, body, table {
            font-family: Muli, sans-serif;
            font-size: 12px;
        }
        .map {
            height: 400px;
            width: 100%;
            border-style: solid;
            border-width: 1px;
            border-color: black;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/build/ol.js"></script>
    <title>OpenLayers example</title>
</head>

<body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([37.41, 8.82]),
          zoom: 4
        })
      });
      
      map.once('rendercomplete', function () {
        window.JSREPORT_READY_TO_START = true;
      });
    </script>
</body>

</html>
```

It gives following Error:

```
Report "test-template" render failed.

Navigation failed because browser has disconnected!
Error: Navigation failed because browser has disconnected!
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/onemapjsreport/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
```

Profile Output:

```
Ok
info
+0
Starting rendering request 3 (user: admin)
info
+1
Rendering template { name: test-template, recipe: chrome-pdf, engine: handlebars, preview: true }
debug
+5
Data item not defined for this template.
debug
+14
Base url not specified, skipping its injection.
debug
+0
Rendering engine handlebars
debug
+83
Executing recipe chrome-pdf
debug
+197
Converting with chrome HeadlessChrome/98.0.4758.0 using chrome-pool strategy
debug
+193
Page request: GET (document) file:///tmp/jsreport/autocleanup/1722c841-be41-470b-a013-1b7fddb22ae9-chrome-pdf.html
debug
+17
Page request finished: GET (document) file:///tmp/jsreport/autocleanup/1722c841-be41-470b-a013-1b7fddb22ae9-chrome-pdf.html
debug
+1
Page request: GET (script) https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/build/ol.js
error
+944
Error when processing render request 3 Navigation failed because browser has disconnected! Error: Navigation failed because browser has disconnected!
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/onemapjsreport/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
error
+0
Rendering request 3 finished with error in 1455 ms
```

**Comment by pofider** [comment] 2022-02-24 08:54
You may need some extra dependencies installed on ubuntu, did you follow this guide?
https://jsreport.net/learn/ubuntu

I see the same error mentioned several times [here](https://github.com/puppeteer/puppeteer/search?q=Navigation+failed+because+browser+has+disconnected%21&type=issues). In one case it was caused by insufficient memory. Does your ubuntu have enough memory? 1GB should be fine.

**Comment by 1Map** [comment] 2022-02-24 10:22
@pofider 

Thanks.  Yes, I did follow exactly the steps to setup.  I am running the latest Ubuntu with enough RAM 128Gb.  

I just setup a new instance of jsreport by following the steps in Ubuntu Setup. 

Personally I think it is not a memory problem, but rather Puppeteer that do a Websocket close before external scripts / css are still loading.  Like in the Orders Sample:

```
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/metro/4.1.5/css/metro.min.css">
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js'></script>
```

I then just run the default Orders Sample that comes with the installation and it still gives the error:

```
Report "orders-main" render failed.

Navigation failed because browser has disconnected!
Error: Navigation failed because browser has disconnected!
    at /home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/jsreportapp/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/jsreportapp/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
``` 

My jsreport.config.json is like:

```
{
  "httpPort": 5499,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "logs/error.log"
    }
  },
  "allowLocalFilesAccess": true,
  "reportTimeout": 60000,
  "workers": {
    "numberOfWorkers": 2
  },
  "extensions": {
    "authentication": {
      "cookieSession": {},
      "admin": {
        "username": "admin",
        "password": "password"
      },
      "enabled": false
    },
    "sample-template": {
      "createSamples": true
    }
  }
}
```

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1152458/155505798-f837c2b8-9ad7-4b6e-95ff-8e6c93532413.png">

**Comment by pofider** [comment] 2022-02-24 10:26
Could you try to run inside docker if it will work for you?
https://jsreport.net/learn/docker

**Comment by 1Map** [comment] 2022-02-24 11:04
Hi @pofider 

No, unfortunately it hangs and come back with an error message:

```
debug+527 Converting with chrome HeadlessChrome/93.0.4577.82 using chrome-pool strategy
error+60000 Error when processing render request 1 Timeout Error: chrome pdf generation not completed after 60000ms Error: Timeout Error: chrome pdf generation not completed after 60000ms
    at Timeout._onTimeout (/app/node_modules/@jsreport/jsreport-chrome-pdf/lib/conversion.js:389:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
error+0 Rendering request 1 finished with error in 61682 ms
```

**Comment by pofider** [comment] 2022-02-24 12:43
Hm, there must be something wrong with the host. 
What version of ubuntu do you use?

I've tried to run now on ubuntu 20.04 and don't have issues
```
docker run -p 5488:5488 -e allowLocalFilesAccess=true jsreport/jsreport:3.4.1
```

**Comment by 1Map** [comment] 2022-02-24 12:53
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

**Comment by pofider** [comment] 2022-02-24 13:07
Ok, I see, unfortunately, I have no further knowledge of how to troubleshoot the chrome/puppeteer. 
Try to start on a different machine as it is likely some host or networking issue.

**Comment by 1Map** [comment] 2022-02-24 13:20
Funny thing is it is just after I upgraded from jsreport 2 to 3 that this happened.  Same server.  All use to work 100% in jsreport 2.

**Comment by 1Map** [comment] 2022-03-07 22:16
@pofider 

I now have more info on puppeteer not connecting:

My template works 100% when using a call to an external css file through:

- http (http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css), 

but fails on a file with:

- https (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css)

**WORKS 100%:**

```
<html>
    <head>
        <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    
    <body>
        <div class="container">
            <h1>Hello world</h1>
        </div>
    </body>
</html>
```

**DOES NOT WORK AND GIVES ERROR:**

```
<html>
    <head>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    
    <body>
        <div class="container">
            <h1>Hello world</h1>
        </div>
    </body>
</html>
```

Error produced:

```
Report "test_bootstrap" render failed.

Navigation failed because browser has disconnected!
Error: Navigation failed because browser has disconnected!
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:271:14)
    at Connection._onClose (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:144:21)
    at WebSocket.<anonymous> (/home/schalk/onemapjsreport/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)
    at WebSocket.onClose (/home/schalk/onemapjsreport/node_modules/ws/lib/event-target.js:210:18)
    at WebSocket.emit (node:events:390:28)
```

**Comment by pofider** [comment] 2022-03-08 19:45
It can be some kind of openssl mismatch, but I'm not an expert on such things.
I see you have already [searched](https://github.com/puppeteer/puppeteer/search?q=Navigation+failed+because+browser+has+disconnected%21&type=issues) the puppeteer issues. Unfortunately, this would be the only recommendation I could provide.
If it's possible, try to install jsreport on a new server.

**Comment by pofider** [comment] 2022-05-04 22:40
I'm afraid I can't help further so I'm closing it.
However, don't hesitate to continue with comments when something pops up.

**Closed by pofider** 2022-05-04 22:40 UTC
