### ISSUE TITLE
Browser IDE

### ISSUE THREAD

**Issue by Siafu** [jsreport/jsreport#126] opened 2015-10-08 17:18 UTC
Is there a way to use my own editor or IDE when developing templates ?

**Comment by bjrmatos** [comment] 2015-10-08 18:14
we're working on it #118 :)

**Comment by Siafu** [comment] 2015-10-08 18:24
Awesome!

**Comment by pofider** [comment] 2015-10-13 14:08
Closing as duplicate of #118 
Please join the discussion in #118 and share your requirements.

**Closed by pofider** 2015-10-13 14:08 UTC
