### ISSUE TITLE
Sign in & Redirect Issue whenever request is sent

### ISSUE THREAD

**Issue by A-Pradeep** [jsreport/jsreport#456] opened 2018-10-11 08:26 UTC
Hi , im using the JSReport in the server and i've create a xlsx template .
In the simple HTML page i have created a simple code , whenever the submission happens:

```
form.on('submit', function (submission) {

                            var data = submission;
                            
                            jsreport.serverUrl = 'http://mydomain.com:5488';

                            var request = {
                                
                                template: {
                                    shortid: "Sk5M6JGcm"
                                },
                                data: data
                            };
                            jsreport.render('_blank', request);                            
                    });
```
Here i written this code and the main problem is

1. that , whenever i click submit , i'll be redirected , and by default the chrome will block the redirect, so how can i download the file without redirecting.

2. If i give redirect access , i'll be asked sign in . so i wanted to know , how can i just download the xlsx template without any sign in or redirect. I've noticed the share link in the `server `studio , but since im new , i have no idea how to use.

Help me out...

**Comment by pofider** [comment] 2018-10-11 11:01
Duplicate of https://forum.jsreport.net/topic/765/report-render-is-very-slow-and-timesout-consistently-after-30sec-with-version-2-2-0/6

**Closed by pofider** 2018-10-11 11:01 UTC

**Comment by A-Pradeep** [comment] 2018-10-11 11:08
But what is the solution for this issue ??
