### ISSUE TITLE
File not found exception when generating a large report

### ISSUE THREAD

**Issue by iamanoopmk** [jsreport/jsreport#734] opened 2020-07-03 13:37 UTC
I am trying to generate a long PDF report using chrome-pdf recipe. After fetching the data I get the error

Error: net::ERR_FILE_NOT_FOUND at file:///tmp/jsreport/autocleanup/e0de1feb-45f8-4579-a659-5e3ada544524-chrome-pdf.html

This only happens when the report being generated is a very large one. Maybe more than 100 pages. 

Any settings that I can use to stop autocleanup of files before rendering?

**Comment by pofider** [comment] 2020-07-06 17:55
Thank you for the bug report.
We clean files after constant 3minutes it was modified the last time. 
However, the HTML is created and immediately read by chrome so it shouldn't happen it gets cleaned.
Are you able to consistently replicate the problem?
Would you be able to share with use your template/export or a repo with problem replication?
Thank you

**Comment by iamanoopmk** [comment] 2020-07-07 03:12
This has been happening for a large report we are generating. Definitely consistent.

The template and data cannot be publically exposed. I will try to see if I can replicate the problem with an example template

**Comment by pofider** [comment] 2020-07-07 06:52
Thank you, that would be great.
I tried various thousands of pages long reports but wasn't able to replicate the problem.

**Comment by pofider** [comment] 2020-08-25 18:42
Closing as it wasn't possible to replicate. Don't hesitate to reopen when you have more details

**Closed by pofider** 2020-08-25 18:42 UTC

**Comment by lichutin-st** [comment] 2021-12-24 08:13
@pofider looks like it's still reproducible on jsreport v2 (v3 works fine). Are there any chances you fix it in the 2.xx version? 

I encountered the error when tried to generate a small pdf when a large one was being generated. The large report completed with success whereas the small one completed with an error.

**Comment by pofider** [comment] 2021-12-26 16:08
@lichutin-st 
I apologize, but currently, we don't plan to merge updates back to v2.
Also, I'm not sure what commit in v3 did actually fix this for you.

**Comment by lichutin-st** [comment] 2021-12-27 05:15
Ok, thanks for the reply.
