### ISSUE TITLE
Running JSReport on Offline Windows server.

### ISSUE THREAD

**Issue by samir-kamble** [jsreport/jsreport#265] opened 2017-02-16 08:54 UTC
Hello Guys,

Thanks for such a wonderful tool. I am trying to install JSReport on Windows server in offline enviroment. I have take all packed package with dependencies within it. Installed it successfully in the system. 

JSreport server started well. I am able to access it within my intranet network. But server suddenly stops randomly when i send a request to it like generate pdf or opening a particular report etc.

I am attaching Debug log here for your reference.

Please help in this regards.

I have updated NPM and NODEJS version also as suggested in error log.

Samir.
[npm-debug.txt](https://github.com/jsreport/jsreport/files/779507/npm-debug.txt)

**Comment by pofider** [comment] 2017-02-16 09:00
So you run something like `node server.js` in the console, but when you open studio and preview a template. It crashes without any message in the console? Did you try this also on an empty html template?
Isn't there an interesting entry in the windows events log?

Can you post the output from the console?

**Comment by samir-kamble** [comment] 2017-02-16 09:03
Thanks....That is quick response man..

I tried this on sample report that is present with the installation. 

here is response from Console 

`C:\Program Files\nodejs>npm start

> jsreport-server@ start C:\Program Files\nodejs
> node server.js

2017-02-16T08:58:33.854Z - info: Initializing jsreport@1.4.0 in development mode
 using configuration file dev.config.json
2017-02-16T08:58:33.885Z - info: Searching for available extensions in C:\Progra
m Files\nodejs\
2017-02-16T08:58:33.917Z - info: Extensions location cache contains up to date i
nformation, skipping crawling in C:\Program Files\nodejs\node_modules\jsreport\n
ode_modules\
2017-02-16T08:58:36.510Z - info: Found 28 extensions
2017-02-16T08:58:36.589Z - debug: Writing extension locations cache to C:\Users\
s-slvuat\AppData\Local\Temp\jsreport-temp\extensions\locations.json
2017-02-16T08:58:36.604Z - debug: Discovered 28 extensions
2017-02-16T08:58:36.620Z - info: Using extension jsrender
2017-02-16T08:58:36.635Z - info: Using extension tags
2017-02-16T08:58:36.667Z - info: Using extension templates
2017-02-16T08:58:36.682Z - debug: Extension authentication is disabled, skipping

2017-02-16T08:58:36.698Z - info: Using extension import-export
2017-02-16T08:58:37.854Z - info: Using extension debug
2017-02-16T08:58:37.870Z - info: Using extension express
2017-02-16T08:58:38.229Z - info: Using extension fop-pdf
2017-02-16T08:58:38.276Z - info: Using extension handlebars
2017-02-16T08:58:38.276Z - info: Using extension phantom-pdf
2017-02-16T08:58:38.511Z - info: Using extension fs-store
2017-02-16T08:58:39.432Z - info: Using extension authorization
2017-02-16T08:58:39.448Z - debug: Extension authorization was disabled
2017-02-16T08:58:39.448Z - info: Using extension data
2017-02-16T08:58:39.464Z - info: Using extension child-templates
2017-02-16T08:58:39.526Z - info: Using extension licensing
2017-02-16T08:58:40.073Z - info: Using extension html-to-xlsx
2017-02-16T08:58:40.375Z - info: Using extension text
2017-02-16T08:58:40.375Z - info: Using extension reports
2017-02-16T08:58:40.417Z - info: Using extension resources
2017-02-16T08:58:40.465Z - info: Using extension browser-client
2017-02-16T08:58:40.479Z - info: Using extension studio
2017-02-16T08:58:40.839Z - info: Using extension images
2017-02-16T08:58:40.886Z - info: Using extension scripts
2017-02-16T08:58:40.886Z - info: Using extension assets
2017-02-16T08:58:40.917Z - info: Using extension scheduling
2017-02-16T08:58:40.979Z - info: Using extension xlsx
2017-02-16T08:58:41.307Z - info: Using extension sample-template
2017-02-16T08:58:41.307Z - info: Using extension public-templates
2017-02-16T08:58:41.323Z - debug: Extension public-templates was disabled
2017-02-16T08:58:41.354Z - info: Initializing fs storage at C:\Program Files\nod
ejs\data
2017-02-16T08:58:41.714Z - info: Creating default express app.
2017-02-16T08:58:41.964Z - info: jsreport server successfully started on http po
rt: 5488
2017-02-16T08:58:41.979Z - info: Veryfing license key free
2017-02-16T08:58:43.339Z - info: Unable to verify license key, assuming free
2017-02-16T08:58:43.370Z - info: reporter initialized
2017-02-16T08:58:47.823Z - debug: OData query on templates
2017-02-16T08:58:47.839Z - debug: OData query on tags
2017-02-16T08:58:47.854Z - debug: OData query on data
2017-02-16T08:58:47.854Z - debug: OData query on images
2017-02-16T08:58:47.870Z - debug: OData query on scripts
2017-02-16T08:58:47.870Z - debug: OData query on assets
2017-02-16T08:58:47.932Z - debug: OData query on xlsxTemplates
2017-02-16T08:58:47.932Z - debug: OData query on schedules
2017-02-16T08:58:47.964Z - debug: OData query on settings
2017-02-16T08:58:48.135Z - debug: OData query on templates
2017-02-16T08:58:48.151Z - debug: OData query on settings
2017-02-16T08:58:51.792Z - debug: OData query on templates
2017-02-16T08:58:51.807Z - debug: OData query on templates
2017-02-16T08:58:51.964Z - debug: OData query on settings
2017-02-16T08:59:07.776Z - info: Starting rendering request 1 (user: null) reque
stId=1
2017-02-16T08:59:07.792Z - info: Rendering template {shortid:SkbquQk7Fl, recipe:
phantom-pdf,engine:handlebars} requestId=1
2017-02-16T08:59:07.792Z - debug: Adding sample data Skc_myQYe requestId=1
2017-02-16T08:59:07.807Z - debug: Executing script B1eq_m1mtg requestId=1
2017-02-16T08:59:08.495Z - debug: Resources not defined for this template. reque
stId=1
2017-02-16T08:59:08.495Z - debug: Rendering engine handlebars requestId=1
2017-02-16T08:59:09.557Z - debug: Compiled template not found in the cache, comp
iling timestamp=Thu Feb 16 2017 00:59:09 GMT-0800 (Pacific Standard Time), reque
stId=1
2017-02-16T08:59:09.557Z - debug: Replaced images [] requestId=1
2017-02-16T08:59:09.575Z - debug: Executing recipe phantom-pdf requestId=1
2017-02-16T08:59:09.575Z - debug: Starting child request to render pdf header re
questId=1
express deprecated req.host: Use req.hostname instead node_modules\jsreport\node
_modules\node.extend\lib\extend.js:44:23
2017-02-16T08:59:09.604Z - info: Starting rendering request 2 (user: null) reque
stId=2
2017-02-16T08:59:09.604Z - info: Rendering template {shortid:SkbquQk7Fl, recipe:
html,engine:handlebars} requestId=2
2017-02-16T08:59:09.620Z - debug: Inline data specified. requestId=2
2017-02-16T08:59:09.620Z - debug: Executing script B1eq_m1mtg requestId=2
2017-02-16T08:59:10.339Z - debug: Resources not defined for this template. reque
stId=2
2017-02-16T08:59:10.355Z - debug: Rendering engine handlebars requestId=2
2017-02-16T08:59:11.355Z - debug: Compiled template not found in the cache, comp
iling timestamp=Thu Feb 16 2017 00:59:11 GMT-0800 (Pacific Standard Time), reque
stId=2
2017-02-16T08:59:11.370Z - debug: Replaced images [] requestId=2
2017-02-16T08:59:11.370Z - debug: Executing recipe html requestId=2
2017-02-16T08:59:11.370Z - debug: Skipping storing report. requestId=2
2017-02-16T08:59:11.386Z - info: Rendering request 2 finished in 1782 ms request
Id=2
2017-02-16T08:59:11.386Z - debug: Starting child request to render pdf footer re
questId=1
2017-02-16T08:59:11.401Z - info: Starting rendering request 3 (user: null) reque
stId=3
2017-02-16T08:59:11.401Z - info: Rendering template {shortid:SkbquQk7Fl, recipe:
html,engine:handlebars} requestId=3
2017-02-16T08:59:11.401Z - debug: Inline data specified. requestId=3
2017-02-16T08:59:11.417Z - debug: Executing script B1eq_m1mtg requestId=3
2017-02-16T08:59:11.870Z - debug: Resources not defined for this template. reque
stId=3
2017-02-16T08:59:11.886Z - debug: Rendering engine handlebars requestId=3
2017-02-16T08:59:12.995Z - debug: Compiled template not found in the cache, comp
iling timestamp=Thu Feb 16 2017 00:59:12 GMT-0800 (Pacific Standard Time), reque
stId=3
2017-02-16T08:59:13.011Z - debug: Replaced images [] requestId=3
2017-02-16T08:59:13.011Z - debug: Executing recipe html requestId=3
2017-02-16T08:59:13.011Z - debug: Skipping storing report. requestId=3
2017-02-16T08:59:13.011Z - info: Rendering request 3 finished in 1610 ms request
Id=3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! jsreport-server@ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsreport-server@ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsreport-server packa
ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsreport-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsreport-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log`

**Comment by pofider** [comment] 2017-02-16 09:08
Thanks. Please try to copy the app somewhere out of `Program Files`. Also try to start it using `node server.js` if there will be something more interesting in the output. Isn't there an actual error in the `logs/error.log`?

**Comment by samir-kamble** [comment] 2017-02-16 09:16
Givin it a try outside program files. Also following is the Error log file attached. 
[error.txt](https://github.com/jsreport/jsreport/files/779575/error.txt)

I was just checking if the same problem happened earlier to anyone. I found this recent conversation but no solution is being posted there as well.

https://groups.google.com/forum/#!topic/jsreport/XuZKyDn96W0

**Comment by pofider** [comment] 2017-02-16 09:26
Thanks, the log gives some info

it seems to crash on this line
https://github.com/pofider/phantom-html-to-pdf/blob/0.4.12/lib/dedicatedProcessStrategy.js#L47

I would need to print out the arguments. The file should be stored here
`node_modules\jsreport\node_modules\phantom-html-to-pdf\lib\dedicatedProcessStrategy.js`

Would you add this to print out arguments? It should be visible then in the console
```js
console.log(requestOptions.phantomPath || options.phantomPath)
console.log(JSON.stringify(childArgs))
console.log(JSON.stringify(childOptions))
```

The problem could be that the phantomjs.exe is not found on the expected path.

**Comment by samir-kamble** [comment] 2017-02-16 09:39
where to put this code? Should I put this on line no 48?

I tried running from outside but it shown error. I guess I need to install from start again for running from outside.

**Comment by pofider** [comment] 2017-02-16 09:39
Yes, before this line

```js
var child = childProcess.execFile(requestOptions.phantomPath || options.phantomPath, childArgs, childOptions, function (err, stdout, stderr) {
```

**Comment by samir-kamble** [comment] 2017-02-16 10:47
Hello ,

I tried generating pdf with new template and one sample line in it. But it gives same error. Also, Following is the output from Console after adding your lines to the file "dedicatedProcessStrategy.js"

2017-02-16T10:40:10.875Z - info: Veryfing license key free
2017-02-16T10:40:12.312Z - info: Unable to verify license key, assuming free
2017-02-16T10:40:12.328Z - info: reporter initialized
2017-02-16T10:41:03.297Z - debug: OData query on templates
2017-02-16T10:41:03.328Z - debug: OData query on tags
2017-02-16T10:41:03.328Z - debug: OData query on data
2017-02-16T10:41:03.344Z - debug: OData query on images
2017-02-16T10:41:03.359Z - debug: OData query on scripts
2017-02-16T10:41:03.375Z - debug: OData query on assets
2017-02-16T10:41:03.406Z - debug: OData query on schedules
2017-02-16T10:41:03.406Z - debug: OData query on xlsxTemplates
2017-02-16T10:41:03.422Z - debug: OData query on settings
2017-02-16T10:41:03.516Z - debug: OData query on templates
2017-02-16T10:41:16.078Z - info: Starting rendering request 1 (user: null) reque
stId=1
2017-02-16T10:41:16.094Z - info: Rendering template {shortid:rJxNyeQYe, recipe:p
hantom-pdf,engine:handlebars} requestId=1
2017-02-16T10:41:16.094Z - debug: Data item not defined for this template. reque
stId=1
2017-02-16T10:41:16.109Z - debug: Resources not defined for this template. reque
stId=1
2017-02-16T10:41:16.125Z - debug: Rendering engine handlebars requestId=1
2017-02-16T10:41:17.219Z - debug: Compiled template not found in the cache, comp
iling timestamp=Thu Feb 16 2017 02:41:17 GMT-0800 (Pacific Standard Time), reque
stId=1
2017-02-16T10:41:17.235Z - debug: Replaced images [] requestId=1
2017-02-16T10:41:17.235Z - debug: Executing recipe phantom-pdf requestId=1
null
["--ignore-ssl-errors=yes","--web-security=false","--ssl-protocol=any","C:\\Prog
ram Files\\nodejs\\node_modules\\jsreport\\node_modules\\phantom-html-to-pdf\\li
b\\scripts\\standaloneScript.js","C:\\Users\\s-slvuat\\AppData\\Local\\Temp\\jsr
eport-temp\\722e6a20-f434-11e6-a022-91bb69cee304settings.html"]
{"env":{"PHANTON_MAX_LOG_ENTRY_SIZE":1000}}

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! jsreport-server@ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsreport-server@ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jsreport-server packa
ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jsreport-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jsreport-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

Also, Attaching error log file for your reference. 
[error.txt](https://github.com/jsreport/jsreport/files/779807/error.txt)

**Comment by pofider** [comment] 2017-02-16 12:08
Thank you. I see from the output that it's passing `null` as phantomjs location and this causes the fail.

I'm assuming you are using standard jsreport installation without phantomjs@2 config....

The phantomjs location is normaly loaded from file `node_modules\jsreport\node_modules\phantom-html-to-pdf\node_modules\phantomjs\lib\location.js`. I assume you don't see this file? This file is supposed to be created during npm install and contains usually this `module.exports.location = "phantom\\phantomjs.exe"`

My current assumption is that your deployment somehow damaged the `location.js` file. 
Maybe you can also reach me on skype @pofider if you want to faster troubleshoot this.

**Comment by samir-kamble** [comment] 2017-02-16 12:20
I guess it was not packaged well when I did it from my machine to server. Since it is a offline install.

I used "npmbox" for packaging it and deploy it on offline server. 

Can you please help in how to go about offline installation of JSReports. We are keen to purchase a licensed copy of JSReports for ourselves once installation goes well.

**Comment by pofider** [comment] 2017-02-16 12:27
It should work just to zip the whole working application on your local and deploy/unzip on the server. Can you try this?

**Comment by samir-kamble** [comment] 2017-02-16 13:09
This worked like charm. Many thanks for help. I was not thought it would be so easy to deploy. 

Will soon be taking license for the product after completion of testing :)...

**Comment by pofider** [comment] 2017-02-16 13:11
Great. 

The problem was very likely caused by using `npmbox` to package jsreport. The recommended way currently is to use simple zip and copy the app. Soon we ship also feature to compile jsreport into single executable.

Closing this.

**Closed by pofider** 2017-02-16 13:11 UTC
