### ISSUE TITLE
http://pagetopdf.com/ is broken. Not work at all.

### ISSUE THREAD

**Issue by audiorecorder** [jsreport/jsreport#165] opened 2016-01-08 06:10 UTC
http://pagetopdf.com/ is broken. Not work at all.

Error occured - Error during rendering report: template is not defined
Stak - ReferenceError: template is not defined
    at C:\jsreport\playground-service\extension\templates-playground\lib\templates.js:59:28
    at _fulfilled (C:\jsreport\playground-service\node_modules\jsreport-mongodb-store\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (C:\jsreport\playground-service\node_modules\jsreport-mongodb-store\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (C:\jsreport\playground-service\node_modules\jsreport-mongodb-store\node_modules\q\q.js:756:13)
    at C:\jsreport\playground-service\node_modules\jsreport-mongodb-store\node_modules\q\q.js:564:44
    at flush (C:\jsreport\playground-service\node_modules\jsreport-mongodb-store\node_modules\q\q.js:110:17)
From previous event:
    at toCb (C:\jsreport\playground-service\node_modules\jsreport\node_modules\jsreport-core\lib\reporter.js:120:21)
    at null.<anonymous> (C:\jsreport\playground-service\node_modules\jsreport\node_modules\jsreport-core\lib\reporter.js:133:5)
    at C:\jsreport\playground-service\node_modules\toner\lib\listeners.js:42:12
    at Array.forEach (native)
    at collection.fire (C:\jsreport\playground-service\node_modules\toner\lib\listeners.js:28:9)
    at Toner.render (C:\jsreport\playground-service\node_modules\toner\lib\toner.js:107:24)

**Comment by pofider** [comment] 2016-01-08 08:50
Thank you. This was caused by playground update we released recently. It is fixed now and should work as before.

**Closed by pofider** 2016-01-08 08:50 UTC
