### ISSUE TITLE
Error: Engine 'handlebars' not found

### ISSUE THREAD

**Issue by jues** [jsreport/jsreport#512] opened 2019-03-14 10:34 UTC
node v8.11.1 mac10.13.6 
`"jsreport": "^2.4.0",`      

config in jsreport.config.json     
```
{
  "httpPort": 5488,
  "store": {
    "provider": "fs"
  },
  "blobStorage": {
    "provider": "fs"
  },
  "logger": {
    "console": {
      "transport": "console",
      "level": "debug"
    },
    "file": {
      "transport": "file",
      "level": "info",
      "filename": "./logs/reporter.log"
    },
    "error": {
      "transport": "file",
      "level": "error",
      "filename": "./logs/error.log"
    }
  },
  "allowLocalFilesAccess": true,
  "templatingEngines": {
    "timeout": 10000,
    "strategy": "http-server"
  },
  "chrome": {
    "timeout": 40000
  },
  "extensions": {
    "assets": {
      "allowedFiles": "**/img/*.*",
      "publicAccessEnabled": true,
      "searchOnDiskIfNotFoundInStore": true,
      "rootUrlForLinks": "http://localhost:5488"
    },
    "authentication": {
      "cookieSession": {
        "secret": "<your strong secret here>"
      },
      "admin": {
        "username": "admin",
        "password": "password"
      },
      "enabled": false
    },
    "scripts": {
      "timeout": 40000,
      "strategy": "http-server"
    }
  }
}
```

code using jsreport      
```
// handling action that was generated from renderer process
  ipcMain.on('render-start', async (event, args) => {
    appLog('info', 'initializing reporter..')

    try {
      // we defer jsreport initialization on first report render
      // to avoid slowing down the app at start time
      if (!jsreport._initialized) {
        await jsreport.init()
        appLog('info', 'jsreport started')
      }

      appLog('info', 'rendering report..')

      try {
        const resp = await jsreport.render({
          template: {
            content: fs.readFileSync(path.join(__dirname, './../../report/report.html')).toString(),
            engine: 'handlebars',
            recipe: 'chrome-pdf'
          },
          data: {
            rows: args
          }
        })

        appLog('info', 'report generated')

        fs.writeFileSync(path.join(CWD, 'report.pdf'), resp.content)

        const pdfWindow = new BrowserWindow({
          width: 1024,
          height: 800,
          webPreferences: {
            plugins: true
          }
        })

        pdfWindow.loadURL(url.format({
          pathname: path.join(CWD, 'report.pdf'),
          protocol: 'file'
        }))

        event.sender.send('render-finish', {})
      } catch (e) {
        appLog('error', `error while generating or saving report: ${e.stack}`)
        event.sender.send('render-finish', { errorText: e.stack })
      }
    } catch (e) {
      appLog('error', `error while starting jsreport: ${e.stack}`)
      app.quit()
    }
  })
```

Error msg after clicking the button     
```
┏ Electron -------------------

  error while generating or saving report: Error: Engine 'handlebars' not found. If this is a custom engine make sure it's properly installed from npm
      at module.exports (/Users/mac/Downloads/electron/node_modules/jsreport-core/lib/util/createError.js:11:13)
      at Reporter.createError (/Users/mac/Downloads/electron/node_modules/jsreport-core/lib/reporter.js:265:12)
      at invokeRender (/Users/mac/Downloads/electron/node_modules/jsreport-core/lib/render/render.js:38:20)
      at module.exports (/Users/mac/Downloads/electron/node_modules/jsreport-core/lib/render/render.js:133:11)
      at <anonymous>
  
┗ ----------------------------
```

BUT the code and config above runs perfectly on win10 with node v10.15.2      

Thank you very mush for any help!

**Comment by bjrmatos** [comment] 2019-03-14 15:02
hmm that looks strange, i guess it is related to some problem when resolving `node_modules` inside electron. since the error is present on macOS i can give it a try (i'm using OSX El Capitan). can you upload a minimal part of your project to github repository (only the parts needed to reproduce the issue)? with that repository i will be able to replicate the issue on my machine

**Comment by jues** [comment] 2019-03-15 02:52
@bjrmatos 
Thank you for the reply!    
and here is the demo: https://github.com/jues/electron-jsreport-demo     
just run     
```
npm install     
npm run dev     
```
then click the generateReport button

**Comment by bjrmatos** [comment] 2019-03-15 16:34
hi! it looks that you were following the instructions that we made in our [pdf reports in electron post](https://jsreport.net/blog/pdf-reports-in-electron-app), great! however your project structure is a bit different from what is described in the post, probably because you are using an starter project.. this matters for some code that are related to paths. for example i was able to fix your project by changing [this line](https://github.com/jues/electron-jsreport-demo/blob/master/src/main/index.js#L26) to this:

```js
const rootDir = process.platform === 'darwin' ? path.resolve(__dirname, '../../') : CWD
```

if you think about that makes sense because in the project from our post the `__dirname` of main file in the project directory, however in your case, your main file is located inside two folders (`src/main`).

just do that change and it should work for you, if it does not try starting the project with this command (just once): `npm run dev -- --useExtensionsLocationCache=false`

you will probably hit another error related to paths when you build the app, so it is worth that you review the variables that contain paths and compare them with what we have in the blog post and adapt your code.

**Closed by bjrmatos** 2019-03-15 16:34 UTC
