### ISSUE TITLE
Update the docker images

### ISSUE THREAD

**Issue by notatestuser** [jsreport/jsreport#320] opened 2017-08-04 07:39 UTC
Would you mind updating the images in the Docker Hub? I \*think\* they were built using the old scripts that produced larger images. Thanks!

**Comment by bjrmatos** [comment] 2017-08-04 14:51
yes, i think the plan is to update the images in docker hub when releasing jsreport v1.8.0, which should be ready in the following days.

**Comment by drmikecrowe** [comment] 2017-08-04 15:09
@bjrmatos will this include a fix for https://github.com/jsreport/jsreport/issues/312?

**Comment by bjrmatos** [comment] 2017-08-04 15:13
@drmikecrowe yes, i think so, we have the cause of the bug, so that error should be solved in the next release.

**Comment by pofider** [comment] 2017-08-11 17:09
Released in 1.8.1

**Closed by pofider** 2017-08-11 17:09 UTC
