### ISSUE TITLE
chrome-pool in .net core doesn't work

### ISSUE THREAD

**Issue by chazt3n** [jsreport/jsreport#795] opened 2021-03-25 12:13 UTC
It generates an unsupported exception. What is the proper way to use chrome pool with .net core?
The documentation is non-existent, but the fluent api code for chrome strategies exists for some reason.

**Comment by pofider** [comment] 2021-03-26 13:18
Duplicate of https://github.com/jsreport/jsreport-dotnet-example-webapp/issues/9

**Closed by pofider** 2021-03-26 13:18 UTC
