### ISSUE TITLE
Layout templates and context based resolution of templates

### ISSUE THREAD

**Issue by JulianRooze** [jsreport/jsreport#51] opened 2015-03-13 12:32 UTC
Hi,

We currently have a .NET application where we use Razor views for the rendering of the emails that we send. We also use Microsoft Reports RDLC reports for rendering invoices and other documents. We'd like to move to jsreport for this as it seems perfect for this. However we like the ability of Razor views to define a layout template that is wrapped around a rendered template. Jsreport offers support for child templates, and I suppose the same could be achieved by rendering a "header" child template at the top of your template and a "footer" child template at the bottom, but something like {{ layout MyLayout }} would be nice and declarative I feel. 

I suppose this is feasible by writing an extension, similar to childTemplates? I'd be up for contributing that, but I have no experience in node development. 

Would it be correct to say I'd have to:
1. Hook into `handleBeforeRender`, 
2. Test it the template contains the {{ layout }} tag
3. If so render that template
4. Back in `handleBeforeRender` replace {{ layout }} with nothing
5. Let the main template be rendered
6. Somehow replace a placeholder in the layout body with the rendered main template
7. Profit?

To be clear, I'm suggesting something like:

Layout:

``` html
<html>
<body>
{{ body }}
</body>
</html>
```

Main template:

``` html
{{ layout MyLayout }}
<p>Hello world</p>
```

Or would you do this in some other way?

My second question is about how to resolve (child)templates dynamically based on context. Currently, our Razor views are resolved based on the context of the current user; mainly his preferred language. The views are organized in a folder structure, something like:

```
views/
    shared/
        nl/
            Layout.cshtml
        en/
            Layout.cshtml
        de/
            Layout.cshtml
    orders/
        nl/
            OrderShipped.cshtml
        en/
            OrderShipped.cshtml
        de/
            OrderShipped.cshtml
    partials/
        nl/
            CustomerAddress.cshtml
        en/
            CustomerAddress.cshtml
        de/
            CustomerAddress.cshtml

```

When we want to send an "your order is shipped" mail, we look at the language of the current user and find the right "OrderShipped.cshtml" mail and render it. That template contains a declaration that it uses Layout.cshtml for its layout so we resolve the right Layout based on the language and it also renders a partial (a child template) for a customer's address that is shared between templates so we resolve the right one for that. 

The first step of finding the right OrderShipped would be no problem with jsreport, but how would this work for the child templates and (my proposed) layout templates?

Would really appreciate some help here :)

**Comment by pofider** [comment] 2015-03-15 21:30
Thanks for the excellent description. The problem is very clear to me after reading it.

Right now in Sunday evening I have the opinion that what you propose is the best. The extension should be very similar to the child templates one and quite easy to implement. 

1. hook into *afterTemplatingEnginesExecutedListeners*
2. if `{#layout foo}` is found, render that specific template into a variable
3. replace the `{#body}` in the previously stored output with the original output with cleared {#layout foo} line


Use `{#xxx }` format for your tags  which won't interfere with the templating engines. 
Use *afterTemplatingEnginesExecutedListeners* hook because it gives you possibility to generate the layout or child template name dynamically based on the context.

The second note probably answers your second question. You just take the right template based on the language using jsrender or handlebars:

`{#layout {{:language}}Theme}` will produce `{#layout enTheme}` assuming you use jsrender and your input data stream contains *language* property with *en* string. This transformation happens before you get into your extension so you then automatically pick up the right one.

**Comment by JulianRooze** [comment] 2015-03-17 12:22
Great, thanks for your answer!

I don't have any node experience but I think I'll manage to write that extension. 

One thing that I'm still confused about is how to provide jsreport with that "enTheme" template. We'll most likely be storing the templates in our own database and while the .NET API allows you to provide the raw template as the `content` field on the `Template` in the `RenderRequest`, it won't be able to resolve that "enTheme" template unless it knows about it. 

I know the .NET API offers the `SynchronizeTemplatesAsync` method, which does something with reading the `.jsrep` files from a bin folder, but it would be nice if there was an API for providing this programmatically so a client could read the templates from its database or any other source and upload them to the reporting server at application startup (in our case).

I'm thinking of something like:

````csharp
_reportingServer.ReportingService.SynchronizeTemplatesAsync(new TemplateDefinition[]
{
	new TemplateDefinition("enTheme", "<h1>Hello!</h1>"),
	new TemplateDefinition("deTheme", "<h1>Guten tag!</h1>"),
});
````

Looking at the source code, this seems doable:

https://github.com/jsreport/net/blob/622eaf21f150a82a4ced6e575cfd918a88b66b9d/jsreport/jsreport.Client/ReportingService.cs#L240

What are your thoughts?

**Comment by pofider** [comment] 2015-03-17 21:50
You are right. If you render just an anonymous template then you have no way to actually specify layout or child templates. In this case you would need to provide the final template directly in the rendering request.

`SynchronizeTemplatesAsync` is designed to work together with [visual studio extension](http://jsreport.net/learn/visual-studio-extension) which stores reports in `.jsrep` files directly in the solution. 

You are free to sync the templates with your own storage in a similar way. Just use [Simple OData Client](https://github.com/object/Simple.OData.Client) which is exposed from the `ReportingService`
```cs
var client = rs.CreateODataClient();
client.client.For<Template>().Set(new Template() { content: "foo" }).InsertEntryAsync();
```

Just for curiosity what is your storage for templates? Are the templates user editable or just static?

**Comment by JulianRooze** [comment] 2015-03-30 17:09
Hi,

Thanks for your reply and sorry, since then I got caught up in other stuff and this is a bit of a side project. 

I started work on this, but one thing I ran into is that while your `{#layout {{:language}}Theme}` syntax would let me dynamically resolve a template, it's possible and even likely in our case that the given template does not exist. We use a fallback system: besides language we also have different templates per brand (sort of, closest analogy I can think of) and per brand we can have different languages. So for example, you might have a template "Nike_en_Invoice" or "Adidas_de_Invoice". That's the most specific template possible in our case. But it's likely that the most specific template does not actually exist and a more generic one does.

While we support multi language, usually it simply doesn't apply. So if the current user is logged in under the English language for the brand "Mercedes" we'll first look for "Mercedes_en_Invoice". If that can't be found (as would usually be the case) we fall back to "Mercedes_default_Invoice". If *that* can't be found, we fall back to "default_default_Invoice". I don't think this is possible currently. 

I think what I need for this is an event that is raised when the `reporter.render` tries to resolve a template and the ability to return a different one. So if the reporter looks for the template `invoice` (which doesn't exist) that it's possible for a subscriber on this event to change that to `invoice_default_default` (which does exist). 

Something like:

```javascript
reporter.resolveTemplateListeners.add(definition.name, this, function(request) {
	
});
```

I would write an extension specific for our application that would use that listener to find the right template for the requested one. 

An additional benefit is that I think it's cleaner to be able to just write `{#layout invoice}` rather than `{#layout {{:language}}invoice}` and would unburden the person who creates a template from considering multi-language/multi-brand scenarios. Another thing is that it would allow graceful degradation if a template doesn't exist at all, the resolver could in that case return a default 404 template, or just an empty one.

Is something like that currently possible that you know of and how would you feel about adding such a hook into the core renderer?

PS: To answer your other question, our templates would eventually be user editable and would be stored in SQL Server.

**Comment by pofider** [comment] 2015-04-03 14:01
Thanks for perfect problem description and sorry for the late response.

This really looks like a problem I would not abstract into reusable extension at least for the start. So lets assume it will be just written for your purpose. 

The child templates extension contains code responsible for searching for the template and you can use the same one just little bit more complex for your case. 
https://github.com/jsreport/jsreport/blob/master/extension/childTemplates/lib/childTemplates.js#L40
I don't see the reason for having such an event like `resolveTemplateListeners` because you would be "resolving" the template by your code anyway.

**Comment by JulianRooze** [comment] 2015-04-03 21:37
Okay, so you're saying that I should essentially copy the childTemplates extension and make it do what I want specifically for our case? I would be okay with that. However, the layoutTemplates extension I was planning to write would have to be capable of the same dynamic template resolution and I think it would have value to be part of the jsreport core capabilities so I was planning to contribute it back. But of course if it will contain logic specifically for our use case then that won't be possible.

**Comment by pofider** [comment] 2017-01-03 18:47
I've blogged how you can implement layout templates using assets and scripts extension.
http://jsreport.net/blog/template-layouts

The same approach could be used to implement also more advanced scenarios.

**Closed by pofider** 2017-01-03 18:47 UTC
