### ISSUE TITLE
Windows 8.1 high dpi issue when generate pdf

### ISSUE THREAD

**Issue by minzdrav** [jsreport/jsreport#54] opened 2015-04-07 11:41 UTC
Hi
I'm trying generate report on my dev laptop, but with default windows scaling settings everything in pdf looks too small. 
When I disable windows scaling and restart pc, everything looks fine. It's not real solution, because every app now looks too small. It's really hard to read something.
Could you please resolve problem?

**Comment by pofider** [comment] 2015-04-07 16:26
Would it be a solution to add zoom to the css style?

https://playground.jsreport.net/#playground/Y3EzYS8Md/4

**Comment by minzdrav** [comment] 2015-04-07 16:47
No. Looks same in pdf. Only zooming when render as html.
Anyway change html property not best solution, because I should be able to publish to server.

**Comment by minzdrav** [comment] 2015-04-08 03:10
It's working only when I insert style tag directly to html, not working from css file.

Maybe problem in phantomjs? I see that jsreport contain not latest version.

**Comment by pofider** [comment] 2015-04-08 07:23
Are the other styles in the referenced css applied? Is the css file referenced with the absolute path? 

phantomjs 1.9.x which jsreport uses is the most stable. The maintainers are waiting for phantomjs 2.0 to fix major bugs and then will switch. If you want you can just download latest phantomjs and override the exe file which is jsreport, but I hardly doubt your issue will be fixed with this.

**Comment by minzdrav** [comment] 2015-04-08 08:45
Yes, other styles from css  applied.

**Comment by pofider** [comment] 2016-12-07 13:55
The problem is likely solved in the phantomjs@2. Here are the docs how to use it with jsreport
http://jsreport.net/learn/phantom-pdf#phantomjs2

**Closed by pofider** 2016-12-07 13:55 UTC
