### ISSUE TITLE
passing JS object to child template

### ISSUE THREAD

**Issue by cesartl** [jsreport/jsreport#315] opened 2017-07-25 10:44 UTC
I saw you can pass parameters to a child template like this:

```
{#child myChildTemplate @data.paramA=foo}
```

Is it possible to pass a JS object instead of the string `foo`?

**Comment by cesartl** [comment] 2017-07-25 10:50
or even passing a string stored in a variable to make it dynamic

**Comment by pofider** [comment] 2017-07-25 11:30
It is possible to pass a string variable using templating engine

```
{#child myChildTemplate @data.paramA={{foo}}}
```

Passing object is not possible at this moment, it is more complex than it looks
https://github.com/jsreport/jsreport-child-templates/issues/1

Referencing here also discussion about child templates docs (not yet updated on web)
https://github.com/jsreport/docs/pull/15

**Comment by cesartl** [comment] 2017-07-25 11:41
when I use

```
 {#child salesReportTable @data.impact={{name}}}
```

I get the error

```
Error occured - Error during rendering report: Parse error on line 7:
... @data.impact={{name}}}
{{/each}}

<h
-----------------------^
Expecting 'CLOSE', 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE_UNESCAPED'
Stak - Error: Parse error on line 7:
... @data.impact={{name}}}
{{/each}}

<h
-----------------------^
Expecting 'CLOSE', 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE_UNESCAPED'
    at Object.parseError (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Object.parse (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at HandlebarsEnvironment.parse (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
    at compileInput (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:514:19)
    at ret (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
    at /usr/src/app/node_modules/jsreport-handlebars/lib/handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.runInNewContext (vm.js:93:38)
```

`name` is a string variable

I'm running the docker image `jsreport:1.7.0-full`

**Comment by pofider** [comment] 2017-07-25 11:55
Ah, I appologize, it seems handlebars requires space before final closing bracket

```
{#child nested @data.foo={{name}} }
```

Demo
https://playground.jsreport.net/studio/workspace/r1RD1nVIZ/4

This will have to come also to the docs, just need to find time to rebuild it.

**Comment by cesartl** [comment] 2017-07-25 11:56
ok that works thanks

**Comment by cesartl** [comment] 2017-07-25 12:07
Is it not possible to pass two `@data` attributes to the child template? When I pass two the 2nd overrides the 1st.

**Comment by pofider** [comment] 2017-07-25 12:19
This was already fixed, but it has not been yet released in full jsreport.
https://github.com/jsreport/jsreport-child-templates/commit/b724aadcd07f08f76a5c68fc86872f3159e54b80

Maybe you can make your own docker image with the latest `jsreport-child-templates`? Or use string concatenation/splitting to workaround it until we push new version.

**Comment by cesartl** [comment] 2017-07-25 12:27
OK thanks

**Comment by pofider** [comment] 2017-07-25 16:21
The main issue here is duplicate of https://github.com/jsreport/jsreport-child-templates/issues/1
Closing in favor of older issue

**Closed by pofider** 2017-07-25 16:21 UTC
