### ISSUE TITLE
The specified executable is not a valid application for this OS platform

### ISSUE THREAD

**Issue by ggmathewtor** [jsreport/jsreport#454] opened 2018-10-03 23:08 UTC
Just upgraded to 2.2.0 (via Nuget) in my .Net core project. Now its throwing error when create a report. My OS is Win10 64bit. It was working until the 2.2.0 upgrade without any issue. What could be the problem?

 System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at jsreport.Local.Internal.BinaryProcess.<InnerExecute>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at jsreport.Local.Internal.BinaryProcess.<ExecuteExe>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at jsreport.Local.Internal.LocalUtilityReportingService.<RenderAsync>d__10.MoveNext()

**Comment by pofider** [comment] 2018-10-04 07:51
Closing to avoid fragmentation of discussion.
This is duplicate of https://forum.jsreport.net/topic/760/error-the-specified-executable-is-not-a-valid-application-for-this-os-platform

**Closed by pofider** 2018-10-04 07:51 UTC
