### ISSUE TITLE
JSReport crashes if there's an empty folder in the data/templates folder

### ISSUE THREAD

**Issue by yarongolan** [jsreport/jsreport#338] opened 2017-09-25 06:03 UTC
017-09-25T06:01:34.507Z - error: Failed to load collection data Error: Unable to parse config.json. Database is corrupted or you are trying to use "fs" jsreportstore provider on the data set created with "nedb" provider. Please switch connection string name to nedb and npm install jsreport-embedded-store
Error: ENOENT: no such file or directory, open '<folder>\data\config.json'
    at ReadFileContext.<anonymous> (<folder>\jsreport-server\node_modules\jsreport-fs-store\lib\persistence.js:304:17)
    at ReadFileContext.callback (<folder>\jsreport-server\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)

**Comment by bjrmatos** [comment] 2017-09-25 14:53
hi! so far i have my `data/templates` (and other folders) empty and i don't see any crash.

<img width="894" alt="captura de pantalla 2017-09-25 a las 9 52 00 a m" src="https://user-images.githubusercontent.com/4262050/30814928-34c74228-a1d7-11e7-9fe7-d4aff10cfec3.png">

(the server has started normally, just that all logs messages don't fit in a single picture)

with a fresh installation, what are the specific steps to reproduce the issue? also make sure to post your OS, and node,npm version.

**Comment by yarongolan** [comment] 2017-09-26 08:20
To reproduce, create an empty subdirectory under data or under templates

**Comment by bjrmatos** [comment] 2017-09-26 15:28
ok now i see the error, thanks. are you manipulating that folder manually? usually jsreport code is the only one that modifies that directoy, are you creating empty directories or something like that for some reason? i will mark the issue as enhancement because in practice it will be very rare to encounter this behaviour.

**Comment by ahallez** [comment] 2017-10-20 17:01
I seem to be running into the same issue.
I start the jsreport server from express
`var express = require('express');

module.exports = {

  init: function(app) {
    var jsreport = require('jsreport')({
      httpPort: 2000,
      connectionString: { 'name': 'fs' },
      dataDirectory: './reports'
    });
    jsreport.init();
  }
};
`
Upon start, the subdirectories of the reports directory are created automatically (and empty).
When I open the studio, the server crashes.

**Comment by bjrmatos** [comment] 2017-10-20 17:50
@ahallez according to the code you are showing, you are trying to start jsreport inside a express app  but it seems like you are not following all the needed steps (like passing the express app instance to jsreport), this can be the cause of your server crashing. check the [example in the docs](https://jsreport.net/learn/adapting-jsreport#attach-to-existing-express-app) for the exact code that you need to use.

**Comment by ahallez** [comment] 2017-10-20 18:43
@bjrmatos I know how to start jsreport as part of an express app, but when I do that, the studio won't work, because some parts of it don't take the relative path into account.
Starting the server as mentioned above, launches it on the root on a different port.
It worked when I didn't add the connectionString, but then the reports were not saved to files either.

**Comment by bjrmatos** [comment] 2017-10-20 19:01
@ahallez as mentioned in the [docs](https://jsreport.net/learn/configuration#basics) `dataDirectory` should be an absolute path not relative, have you tried that? otherwise it is impossible to tell you what is wrong with just simple snippet of code, try to share more code/information or create a repository with the failing app so i can tell you what could be wrong specifically

**Comment by ahallez** [comment] 2017-10-21 16:47
The problem is definitely related to the fs storage.
If I run this
`    var jsreport = require('jsreport')({
      httpPort: 2000
    });
    jsreport.init();
`
Everything works fine. I can render reports, use the studio, etc... only my template is not preserved between server restarts.
When I run 
`var jsreport = require('jsreport')({
      httpPort: 2000,
      connectionString: { 'name': 'fs' }
    });
    jsreport.init();`
The server starts fine, I can render a report (not using any stored templates).
On the server a data folder with subfolders is created in the root of the project.
The server crashes as soon as I try to open the studio. 
The problem seems to be related to the websocket message handler in the fs extension. This is the error I found in the log file:
`2017-10-21T16:45:21.499Z - error: uncaughtException: Cannot read property 'unmask' of undefined date=Sat Oct 21 2017 18:45:21 GMT+0200 (Romance Daylight Time), pid=10152, uid=null, gid=null, cwd=C:\ScoreExpress\loopback, execPath=C:\Program Files\nodejs\node.exe, version=v8.2.1, argv=[C:\Program Files\nodejs\node.exe, C:\ScoreExpress\loopback\server\server.js], rss=202203136, heapTotal=171126784, heapUsed=127313160, external=1923975, loadavg=[0, 0, 0], uptime=565641.2737443, trace=[column=46, file=C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js, function=Receiver.unmask, line=306, method=unmask, native=false, column=25, file=C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js, function=Receiver.finish, line=505, method=finish, native=false, column=33, file=C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js, function=Receiver.expectHandler, line=493, method=expectHandler, native=false, column=24, file=C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js, function=Receiver.add, line=103, method=add, native=false, column=20, file=C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\WebSocket.js, function=Socket.realHandler, line=825, method=realHandler, native=false, column=13, file=events.js, function=emitOne, line=115, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=210, method=emit, native=false, column=12, file=_stream_readable.js, function=addChunk, line=252, method=null, native=false, column=11, file=_stream_readable.js, function=readableAddChunk, line=239, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=197, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=589, method=onread, native=false], stack=[TypeError: Cannot read property 'unmask' of undefined,     at Receiver.unmask (C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js:306:46),     at Receiver.finish (C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js:505:25),     at Receiver.expectHandler (C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js:493:33),     at Receiver.add (C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\Receiver.js:103:24),     at Socket.realHandler (C:\ScoreExpress\loopback\node_modules\jsreport-fs-store\node_modules\ws\lib\WebSocket.js:825:20),     at emitOne (events.js:115:13),     at Socket.emit (events.js:210:7),     at addChunk (_stream_readable.js:252:12),     at readableAddChunk (_stream_readable.js:239:11),     at Socket.Readable.push (_stream_readable.js:197:10),     at TCP.onread (net.js:589:20)]`

**Comment by bjrmatos** [comment] 2017-10-21 17:15
> The problem is definitely related to the fs storage.
> If I run this
> var jsreport = require('jsreport')({ httpPort: 2000 }); jsreport.init();
> Everything works fine. I can render reports, use the studio, etc... only my template is not preserved between server restarts.

assuming that you don't have any jsreport configuration file in your project (like `dev.config.json`) the default options when jsreport is initialized without any config is to use a memory store, that is the reason for your templates not being preserved between server restarts, because everything is just in memory.



> When I run
> var jsreport = require('jsreport')({ httpPort: 2000, connectionString: { 'name': 'fs' } }); jsreport.init();
> The server starts fine, I can render a report (not using any stored templates).
> On the server a data folder with subfolders is created in the root of the project.
> The server crashes as soon as I try to open the studio.
> The problem seems to be related to the websocket message handler in the fs extension. This is the error I found in the log file:

ok, that sounds like a bug but running the following does not give me any error when running it on OSX with node 8.6.0. 

<img width="1212" alt="captura de pantalla 2017-10-21 a las 12 12 29 p m" src="https://user-images.githubusercontent.com/4262050/31854067-23d43232-b659-11e7-81c3-a43ceffc356e.png">

(i've created a template `foo` with the studio)

if this is just the sample needed to make it fail on windows i will try to reproduce it later (on my windows VM), additionally, i guess you are using latest version of jsreport (1.8.2), right? what is your node and npm version?

**Comment by ahallez** [comment] 2017-10-21 18:16
I have just upgraded node and reloaded all npm modules, so I should be on the latest version.
The issue seems to be with the way the websocket component loads native modules, such as bufferutil.
There native modules are structured differently than the fallback modules that are includes with the ws module.

**Comment by bjrmatos** [comment] 2017-10-22 19:49
woah that are a lot of packages involved.. what i would try is to isolate the problem by creating a new project with just jsreport installed in it. if you don't see this error in such simple project then maybe something in combination with your dependencies is causing this (seems like you are using jsreport with loopback, but i don't know the exact code that you are using to glue the two).

i've tried to reproduce the issue on my windows 10 VM (with node 8.6.0, npm 5) but still don't see anything, everything is working normally.

![captura de pantalla 2017-10-22 a las 2 32 55 p m](https://user-images.githubusercontent.com/4262050/31865556-0548de3e-b736-11e7-9f01-7f5b6e96a7a1.png)

(i've created foo template from studio)

maybe your machine is not [configured properly to compile nodejs native modules](https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#compiling-native-addon-modules) or maybe you need to reinstall the dependencies with a command line with administrative privileges just to discard anything related to folder permissions on your machine.

as i said before and if you need more help try to setup a repository with just the minimal code necessary to reproduce the issue but in the context of your app (for example with loopback installed).

**Comment by pofider** [comment] 2018-03-08 13:34
Closing as here is missing activity.
In every case the v2 has completely rewritten fs store.

**Closed by pofider** 2018-03-08 13:34 UTC
Labels: enhancement
