### ISSUE TITLE
Highcharts Stacked bar chart issue

### ISSUE THREAD

**Issue by minzdrav** [jsreport/jsreport#55] opened 2015-04-09 09:51 UTC
Hi!
Bars too small, please look at example from highcharts site:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-stacked/
https://playground.jsreport.net/#playground/e77zeliQO/49

**Comment by pofider** [comment] 2015-04-09 10:00
This is because of the animation. You can either set "print delay" property with a value like 1000 or disable animations in the highchart like it's done on the original example.

**Comment by minzdrav** [comment] 2015-04-09 10:52
Thank you! You save my day!

**Comment by pofider** [comment] 2015-04-19 16:31
Closing, this is not a bug and also mentioned in FAQ

**Closed by pofider** 2015-04-19 16:31 UTC

**Comment by mukulsoftwap** [comment] 2018-01-23 15:22
![image](https://user-images.githubusercontent.com/7465121/35283827-3fa7a99c-007f-11e8-9ac3-bb652e0a6352.png)
My Chart also shows very small. i have try to add print delay but not work

**Comment by bjrmatos** [comment] 2018-01-23 21:26
hi @mukulsoftwap, have you tried to disable animations in the Highcharts library? when animations are used it makes the chart to appear sometime later and causing that content is not ready/visible when producing the pdf report. also for better clarity, can you share a jsfiddle link with the expected chart and another link (in [jsreport playground](playground.jsreport.net)) with the current output? that will help in understand the differences between the expected and current output.
