### ISSUE TITLE
Electron pdf recipe

### ISSUE THREAD

**Issue by pofider** [jsreport/jsreport#125] opened 2015-10-05 16:15 UTC

**Comment by bjrmatos** [comment] 2015-10-25 23:09
ok i have started the electron implementation with [electron-workers](https://github.com/bjrmatos/electron-workers), and it works like a champ in OSX (should work, unfourtanely i discovered that because electron is not a headless process (for now) it won't work on linux (you can see the travis build logs in `electron-workers` repo).. but the good news is that this will be solved atom/electron#228.. until then i will continue with the development of
[electron-html-to-pdf](https://github.com/bjrmatos/electron-html-to-pdf) and when the issue is resolved all will be ready.

**Comment by bjrmatos** [comment] 2015-10-25 23:36
notes about `electron-workers` implementation:

basically the implementation is heavily based on `phantom-workers` but with the following differences:

1.- ES6 :smile: 

2.- simple [round robin task distribution](https://github.com/bjrmatos/electron-workers/blob/master/src/ElectronManager.js#L116) across workers.. so each worker process is never marked as busy (unless it is recycled), instead one task per worker will be distributed. since electron is not a heavy (buggy?) process like phantom this will work fine in scale.

3.- i only recycle the worker process if a `timeout` is reached, not if the worker return an error. seems like electron have ways to detect if a process is frozen, so in the future i was thinking that the electron script can trigger a process recycle on its own with an event emitter mechanism (something i will explore more in the future)

**Comment by bjrmatos** [comment] 2015-11-27 15:18
just to report that i'm very close to finish the electron recipe, the hard work is done, i just need to write some docs and make the jsreport integration

**Comment by pofider** [comment] 2015-11-27 15:34
Great! I am looking forward.
Feel free to ask for help with jsreport integration. I guess you will just need to add some inputs to UI, I can do it for you if you will want.

**Comment by bjrmatos** [comment] 2015-11-27 15:42
thnks, i will let you know if i have some trouble :smile:

**Comment by bjrmatos** [comment] 2015-12-08 22:11
done and published in npm! :tada: :balloon:

**Closed by bjrmatos** 2015-12-08 22:11 UTC
Labels: enhancement
