### ISSUE TITLE
Progressively increasing rendering time

### ISSUE THREAD

**Issue by JulianRooze** [jsreport/jsreport#78] opened 2015-05-29 13:47 UTC
Hi,

I've tried stress testing jsreport a bit on my local machine, by sending 1000 rendering requests. What I found was that the rendering time started out fast (the order of 200 ms) and then got progressively worse with basically every request, running up to 2000 ms at a certain point where I stopped it. 

At first I assumed it might have something to do with my custom extensions or my complex template so to eliminate that possibility I did a fresh install of jsreport and created a very simple test report with the contents `<h1>test</h1>` and ran my test again. The results were the same, it started under 100 ms and when all 1000 requests were finished it had gone up to 1000 ms. 

My test environment:

OS: Windows 8.1 64-bit
jsreport: 0.6.3
node: 0.12.4 (ran from the commandline) and also tried it with 0.12.0
template recipe: html 
jsreport config: all default values, so 1 worker process

Reproducing my test results should be easy, by following the installation steps for Windows, creating a simple report and calling the render API 1000 times (I did it from the .NET client for jsreport). 

A graph mapping the render time (vertical) for 1000 renders:

![image](https://cloud.githubusercontent.com/assets/1694905/7883434/d839da42-0616-11e5-9acb-d37b4b8bf94c.png)

I tried profiling with https://github.com/node-inspector/node-inspector but couldn't really find anything useful in the CPU profiles (it just said 95% of the time went into program.js) or the heap dumps. 

It didn't seem to matter whether or not you did 1000 requests in a `for` loop, or 1000 requests spread over a large amount of time, they got progressively slower in both cases. So that would mean that if we rendered a 1000 reports during the day, it would be 10x slower by the end of it. This would pose a bit of an issue for us in production use (we would render about 10k reports a day right now) :)

Memory usage of the node.exe process also increases steadily, to over 900 MB. 

Hoping someone else can reproduce this and perhaps find out what's going on :)

**Comment by pofider** [comment] 2015-05-29 14:16
Thanks for excellent bug report. I will check during the weekend and come back to you.

**Comment by pofider** [comment] 2015-05-30 10:40
Verified!

The cause of the problem is in node.js bug https://github.com/joyent/node/issues/6552
jsreport is trying to prevent this bug already for some time by forcing GC, unfortunately this workaround somehow stopped to work. 

Solutions..
- install io.js instead of node.js where the bug is already fixed. Hopefully the bugfix will be merged soon into node.js

I will investigate more on this and hopefully finds a solution for the node.js as well.

**Comment by JulianRooze** [comment] 2015-05-30 14:22
Thanks for your rapid investigation! 

Interesting bug. I will try to see if I can run jsreport on io.js.

**Comment by JulianRooze** [comment] 2015-05-30 14:34
I can verify that running jsreport on io.js solves this bug. And in general, rendering seems to be significantly faster (~60ms for a simple report compared to ~100ms best case for current node).

**Comment by pofider** [comment] 2015-05-30 19:55
Yes, io.js seems to be quite faster, probably because of the newer V8....

I was able workaround the node.js bug and just released jsreport hotfix 0.6.4

**Comment by JulianRooze** [comment] 2015-05-31 17:08
Thanks for the quick fix! I can confirm that the slowdown no longer occurs in 0.6.4 running under node.

**Comment by pofider** [comment] 2015-05-31 19:05
Thanks for confirmation. I guess we can close this now....

**Closed by pofider** 2015-05-31 19:05 UTC
