### ISSUE TITLE
Error during rendering report

### ISSUE THREAD

**Issue by danieloquendo** [jsreport/jsreport#307] opened 2017-07-06 13:33 UTC
I'm working on a web application using phantom-html-to-pdf, localmente works but in production the following error occurs

Error during rendering report: spawn /opt/venfi/node_modules/phantom-html-to-pdf/node_modules/phantomjs/lib/phantom\phantomjs.exe ENOENT

Centos 
Node v6.10.3

Any idea what could be the issue here?
Thank you.

**Comment by bjrmatos** [comment] 2017-07-06 15:55
closing as duplicate of pofider/phantom-html-to-pdf#68

**Closed by bjrmatos** 2017-07-06 15:55 UTC
