### ISSUE TITLE
Unexpected token S in JSON at position 0

### ISSUE THREAD

**Issue by bt-ihsanakin** [jsreport/jsreport#738] opened 2020-07-17 14:59 UTC
When I use jsreport.client.ReportServer class to send a request to render a report, it gives following Error.

2020-07-17T14:47:37.281Z - info: Starting rendering request 1 (user: null)
2020-07-17T14:47:37.284Z - info: Rendering template { name: QuickProposal, recipe: phantom-pdf, engine: handlebars, preview: false }
2020-07-17T14:47:37.286Z - debug: Inline data specified.
2020-07-17T14:47:37.287Z - debug: Resources not defined for this template.
2020-07-17T14:47:37.290Z - debug: Executing script QuickProposal using dedicated-process strategy
2020-07-17T14:47:41.081Z - warn: Rendering request 1 finished with error in 3800 ms
2020-07-17T14:47:41.083Z - warn: Error when processing render request 1 Unexpected token S in JSON at position 0 SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (evaluate-user-script.js:37:38)
    at Object.base.apply (C:\jsreport2\node_modules\vm2\lib/contextify.js:166:34)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2020-07-17T14:47:41.084Z - warn: Error during processing request at http://localhost:5488/api/report

The project that contains jsreport.client.reportServer reference is a .Net 5 Api project. 
Normally I can run the following from an API projet that targets .net framework 4.7 . I suspected JSON serialization difference between .Net core and non-.net core projects.  But how can I detect and solve the error?

**sample code** 
```

  var id = HttpContext.Request.Form["id"].ToString();
            var credentials = Utils.GetCredentials(User);
            var reportingConfigurations = await UtilHelper.GetReportingConfigurations();
            var urlLocationConfig = reportingConfigurations.FirstOrDefault(c => c.Path.Equals("/serverUrl", StringComparison.CurrentCultureIgnoreCase));
            var rs = new ReportingService(urlLocationConfig.ValueString);
            var data = new
            {
                credentials = credentials,
                id = id,
                limit1 = GetFormValue<decimal>(HttpContext.Request.Form, "limit1 ", null),
                limit2= GetFormValue<decimal>(HttpContext.Request.Form, "limit2", null),
                hostName = HttpContext.Request.Host.Host,
                hostPort = HttpContext.Request.Scheme == "http" ? 80 : 443,
                hostPath = HttpContext.Request.PathBase
            }; 

            var report = await rs.RenderByNameAsync(reportName, data); <-- error  occurs here.

```

**Comment by pofider** [comment] 2020-07-17 18:17
The problem is probably in your custom script "QuickProposal".
Could you share its code?

**Comment by pofider** [comment] 2020-08-19 16:57
Closing because of lost the activity, but feel free to continue with the comments.

**Closed by pofider** 2020-08-19 16:57 UTC
