### ISSUE TITLE
file contents not updating upon import

### ISSUE THREAD

**Issue by SankalpJadon** [jsreport/jsreport#385] opened 2018-02-20 20:03 UTC
Hi all,

I am having trouble importing content from my local to our other environments. 
Basically, whenever we import the new updated template from export.zip, the import is successful, but the change doesn't reflect in qa and prod. 
Is this a common issue that i'm unaware of?

Thanks,
Sankalp

**Comment by SankalpJadon** [comment] 2018-02-20 20:04
@pofider will appreciate your inputs

**Comment by pofider** [comment] 2018-02-20 20:20
What template store do you use? The default one using file system?
Are you able to replicate this also on local with some random templates?
Would you be able to share the export zip?
What jsreport version you use? And what os?

**Comment by SankalpJadon** [comment] 2018-02-21 21:25
Template store- I'm using default one, using file system.

Local export and import works, I'm testing on my local machine(windows 10) and our dev server(windows 2012 r2) both. If i'm exporting from dev server and importing in local, or if i'm exporting from local and importing to dev server it doesn't work. However if I'm exporting from server and importing to the same server, or local to local, it works.

We are using jsreports 1.9.2 on windows 10 machines on local, and windows 2012 r2 servers.

Unfortunately I can't share exact report
[export.zip](https://github.com/jsreport/jsreport/files/1745759/export.zip)
, but I can share a test report which doesn't work too.

Thanks,
Sankalp

**Comment by pofider** [comment] 2018-02-21 22:08
Hm, I import this package. Update template. Import again. And it gets correctly imported.

We do write a ["silent" log](https://github.com/jsreport/jsreport-import-export/blob/master/lib/exports.js#L192) in case the update internally fails. Can you check the jsreport log after import? Is there something interesting you can share?

**Comment by SankalpJadon** [comment] 2018-02-21 23:57
I see this-

warn: Unable to upsert an entity during the import Error: Duplicated entry for key test

**Comment by pofider** [comment] 2018-02-26 12:50
I apologize for the delay. 

> warn: Unable to upsert an entity during the import Error: Duplicated entry for key test. Does this mean I can't update files of same name? very wierd!

This would mean that you have on the target instance a template which has name `test` but it has a different `_id` than the template you are trying to insert.
Would you be able to share the exact export you are trying to import (if it is different than the one you shared already) and the zipped `data` folder from jsreport application directory?

**Comment by bjrmatos** [comment] 2018-02-26 18:01
hi! 

i can confirm that importing does not update entity with same name in the following case:

- you have jsreport on one machine (let's call it "local"), then you create a template with name "random", at that point that entity has an `_id`
- you have jsreport on another machine (let's call it "dev"), then you create a template with name "random", at that point that entity has a new `_id`, completely different that the `_id` on "local" machine.
- then you try to export from "local" machine (the export zip will contain the template with name "random" with the `_id` that was generated on the creation)
- then you try to import on "dev" machine the exported zip of "local", when you do that the "dev" machine already has a "random" template with an `_id` different than the one on "local" machine, since both are two different records (different `_id`) instead of updating, jsreport will try to create a new entity, and when doing that it will fail with the message `Unable to upsert an entity during the import Error: Duplicated entry for key random`

the summary is that importing does not update entities when origin ("local" machine) and target ("dev" machine) of import/export has created an entity with same name independently. we will probably detect this problem (entities with same name but with different _id) and just delete the target entity ("dev" machine) first and then insert the one from origin ("local" machine), so instead of an update it will be a replace.

not sure how this happened to you but the best advice that we can give you is that you should treat your dev server as just a copy of local. your dev server should only sync with your local source (maybe using git or just simply delete data folder on dev server before doing a full import, or just deleting specific entities before importing just some entities), not a place where you create templates independently (at least until we solve the bug). 

as a workaround you can for now update your dev server to match entities `_id` in local vs dev with one of the following options:

- do a full export of your local server, delete data folder on dev server and import there the full zip of local server. after that you should have now all the `_id` fields of entites matching, so future import/export will work as updates.
- or before importing an entity, make sure to delete first the entity on dev server and then import. you should only need to do this once per conflicting entity, after that future import/export updates of entities should work.

and as a final note, remember that for now (until we solve the bug) you should not create anything on dev server, just make it a copy of local.

**Comment by pofider** [comment] 2018-02-27 17:36
This is not a bug, it is by design. We match entities by id intentionally because other stores support multiple entities with the same name. This will get even to the fs store when we support the hierarchy. Also matching by id makes better experience when someone is renaming the entities. However I see this is not obvious so we will add message to the import validation dialog for now.

What is rather missing in import-export extension is ability (checkbox) to do full import. This means that all existing entities not present in import package will be deleted. This would also solve this use case.
The tracking issue is [here](https://github.com/jsreport/jsreport-import-export/issues/6). The reason why it was not implemented originally was that I wanted to wait a bit until the extension is stable.

It could happen we change our mind during the implementation with hierarchy and start matching entities by name and path. However I would wait until we get to the implementation of this feature now.

**Comment by pofider** [comment] 2019-04-16 19:39
I close this as it is mostly duplicate of https://github.com/jsreport/jsreport/issues/532
We don't plan to change the logic and keep matching by _id.
Additionally, we implemented a feature for importing into a specific folder and we plan to further improve it.

**Closed by pofider** 2019-04-16 19:39 UTC
